export const FETCH_MOVIES_PENDING = 'FETCH_MOVIES_PENDING';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';

export const FETCH_BASE_CONFIGS_PENDING = 'FETCH_BASE_CONFIGS_PENDING';
export const FETCH_BASE_CONFIGS_SUCCESS = 'FETCH_BASE_CONFIGS_SUCCESS';

export const FETCH_MOVIE_DETAILS_PENDING = 'FETCH_MOVIE_DETAILS_PENDING';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';

export const FETCH_MOVIE_CREDITS_PENDING = 'FETCH_MOVIE_CREDITS_PENDING';
export const FETCH_MOVIE_CREDITS_SUCCESS = 'FETCH_MOVIE_CREDITS_SUCCESS';

export const SEARCH_MOVIE_PENDING = 'SEARCH_MOVIE_PENDING';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';

export const SHOW_HOMEPAGE = 'SHOW_HOMEPAGE';
export const HIDE_HOMEPAGE = 'HIDE_HOMEPAGE';