export const FETCH_MOVIES_PENDING = 'FETCH_MOVIES_PENDING';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';

export const FETCH_BASE_CONFIGS_PENDING = 'FETCH_BASE_CONFIGS_PENDING';
export const FETCH_BASE_CONFIGS_SUCCESS = 'FETCH_BASE_CONFIGS_SUCCESS';

export const FETCH_MOVIE_DETAILS_PENDING = 'FETCH_MOVIE_DETAILS_PENDING';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';

export const FETCH_MOVIE_CREDITS_PENDING = 'FETCH_MOVIE_CREDITS_PENDING';
export const FETCH_MOVIE_CREDITS_SUCCESS = 'FETCH_MOVIE_CREDITS_SUCCESS';

export const SEARCH_MOVIE_PENDING = 'SEARCH_MOVIE_PENDING';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';

export const SHOW_HOMEPAGE = 'SHOW_HOMEPAGE';
export const HIDE_HOMEPAGE = 'HIDE_HOMEPAGE';

export const SHOW_WATCHLIST = 'SHOW_WATCHLIST';

export const ADD_TO_WATCH_LIST_SUCCESS = 'ADD_TO_WATCH_LIST_SUCCESS';
export const ADD_TO_WATCH_LIST_PENDING = 'ADD_TO_WATCH_LIST_PENDING';

export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const HIDE_LOGIN_POP_UP = 'HIDE_LOGIN_POP_UP';
export const SHOW_LOGIN_POP_UP = 'SHOW_LOGIN_POP_UP';

export const FETCH_WATCH_LIST_PENDING = 'FETCH_WATCH_LIST_PENDING';
export const FETCH_WATCH_LIST_SUCCESS = 'FETCH_WATCH_LIST_SUCCESS';
